services:
  - type: web
    name: ecforce-slack-notifier
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    plan: free
    envVars: []
    autoDeploy: true
    region: oregon
    ports:
      - 10000
